# Generated by Django 5.0 on 2024-02-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre'],
            },
        ),
    ]
